### ISSUE TITLE
Add new process method

### ISSUE THREAD

**Issue by criocere** [codeka/carrot#33] opened 2019-03-14 07:34 UTC
My template in already in memory, will it be possible to add a new process method signature with a template as a string as an input argument ?

**Comment by criocere** [comment] 2019-03-14 12:56
Just saw a solution here. This can be closed
https://github.com/codeka/carrot/issues/31

**Comment by codeka** [comment] 2019-03-18 13:03
Dupe of #31

**Closed as completed** 2019-03-18 13:04 UTC
Labels: duplicate
